<a href="https://colab.research.google.com/github/Nataliaa1994/data-science/blob/master/intro_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
x = np.array([1,3])
x

array([1, 3])

In [0]:
print(x)

[1 3]


In [0]:
type(x)

numpy.ndarray

In [0]:
x.ndim

1

In [0]:
x.shape

(2,)

In [0]:
x.size

2

In [0]:
x.dtype

dtype('int64')

In [0]:
x=np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [0]:
x=np.array([[1,2],[-3,1]])
print(x)

[[ 1  2]
 [-3  1]]


In [0]:
A=np.array([1,2,3], dtype='float')
print(A)

[1. 2. 3.]


In [0]:
A=np.array([1,2,3], dtype='complex')
print(A)

[1.+0.j 2.+0.j 3.+0.j]


In [0]:
A=np.array([1.3,2.3,1.4], dtype='int')
A.dtype

dtype('int64')

In [0]:
A

array([1, 2, 1])

In [0]:
A=np.array([120,24,35], dtype='int8')
print(A)

[120  24  35]


In [0]:
A=np.array([True,False])
A.dtype

dtype('bool')

In [0]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.zeros(shape=(4,10), dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
np.ones(shape=(4,10), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [0]:
np.full(shape=(4,4), fill_value=5,dtype="int")

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
range(10)

range(0, 10)

In [0]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [0]:
np.arange(start=20,stop=100,step=10)

array([20, 30, 40, 50, 60, 70, 80, 90])

In [0]:
np.arange(start=100,stop=10,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [0]:
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [0]:
A=np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [0]:
A+B

array([6, 0, 7, 4])

In [0]:
A-B

array([0, 2, 1, 0])

In [0]:
A*B

array([ 9, -1, 12,  4])

In [0]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [0]:
A+3

array([6, 4, 7, 5])

In [0]:
2*A

array([6, 2, 8, 4])

In [0]:
np.add(A,B)

array([6, 0, 7, 4])

In [0]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [0]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [0]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [0]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X,'\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [0]:
X*Y

array([[6, 0],
       [2, 0]])

In [0]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [0]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [0]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [0]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [0]:
np.random.seed(0)

In [0]:
np.random.randn(10)

array([-1.43717771,  0.64467041, -1.21979106,  1.33860403,  2.24368834,
        1.52163169,  0.99650488,  0.64607238, -0.22128649,  0.33154287])

In [0]:
np.random.randn(10,4)

array([[-0.85149184,  1.55174892,  0.57735977, -2.71009688],
       [-0.52534428, -0.22060924, -0.3274101 ,  1.22278861],
       [ 0.50853708,  0.53586449, -0.41649565,  0.12604369],
       [ 1.27374326,  0.2646564 ,  0.6261174 , -0.9887793 ],
       [-0.68688926, -0.95368038, -0.72758044,  1.45609212],
       [-0.03381189, -2.29014558, -1.58971293, -1.13932301],
       [-0.11993045, -1.09244077, -1.0772423 , -0.79696496],
       [ 0.37473292,  0.18864039, -0.46067504,  1.15030438],
       [-0.19931048, -0.53083268, -2.64951384, -1.20877778],
       [-0.03464757,  0.57922173,  0.64529427, -0.50035309]])

In [0]:
np.random.randn()

-0.2983293800202995

In [0]:
np.random.rand()

0.21605845535021817

In [0]:
np.random.randint(10)

9

In [0]:
np.random.randint(low=10,high=101,size=5)

array([31, 13, 99, 21, 78])

In [0]:
np.random.choice([4,2,1,4])

4

In [0]:
np.random.choice(['python','sql','java'])

'java'

In [0]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.random.shuffle(data)

In [0]:
data

array([5, 3, 7, 8, 0, 6, 4, 9, 1, 2])

In [0]:
np.exp(1)

2.718281828459045

In [0]:
np.sqrt(9)

3.0

In [0]:
np.all([2,3,1])

True

In [0]:
np.any([1,2,3])

True

In [0]:
A=np.random.rand(5)
A

array([0.95289297, 0.13253135, 0.1979911 , 0.31707529, 0.43200645])

In [0]:
np.argmax(A)

0

In [0]:
A[np.argmax(A)]

0.9528929675405324

In [0]:
A[np.argmin(A)]

0.132531349618486

In [0]:
np.argsort(A)

array([1, 2, 3, 4, 0])

In [0]:
np.max(A)

0.9528929675405324

In [0]:
np.mean(A)

0.4064994306650771

In [0]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
#A[idx], A[start::stop], A[:stop], A[start:]

In [0]:
A[2]

2

In [0]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [0]:
A[[0,2]]

array([0, 2])

In [0]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
A[:,-2]

array([ 3,  8, 13, 18])

In [0]:
A[1,1]

6

In [0]:
A[1,3]

8

In [0]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [0]:
A[1,2]=14

In [0]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [0]:
for row in A:
  print(row[0])

0
5
10
15


In [0]:
for row in A.flat:
  print(row[0])

In [0]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmairu tablic:

In [0]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
A.shape

(4, 5)

In [0]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [0]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne:

In [0]:
A=np.arange(start=-10,stop=10,step=0.5)
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [0]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [0]:
A>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [0]:
np.bitwise_and(A>-5 , A<5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [0]:
A[np.bitwise_and(A>-5 , A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [0]:
A[np.bitwise_or(A>-5 , A<5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

Algebra liniowa (norma wektora i odległość punktów):

In [2]:
import numpy as np
np.__version__

'1.18.3'

In [6]:
v1=np.array([-1,3])
v1

array([-1,  3])

In [7]:
np.linalg.norm(v1)

3.1622776601683795

In [8]:
v2=np.array([-10,10,12])
np.linalg.norm(v2)

18.547236990991408

In [10]:
p=np.array([3,0])
q=np.array([0,4])

np.linalg.norm(p-q)

5.0

In [11]:
p=np.array([3,0,2])
q=np.array([0,4,1])

np.linalg.norm(p-q)

5.0990195135927845

Algebra liniowa( mnożenie macierzy):

In [14]:
X=np.array([[5,2],[4,1]])
Y=np.array([[2],[-2]])
print(X)
print(Y)

[[5 2]
 [4 1]]
[[ 2]
 [-2]]


In [16]:
Z=np.dot(X,Y)
Z


array([[6],
       [6]])

In [18]:
X=np.array([[3,2,-1],
            [4,1,1]])
Y=np.array([[2,-1,1],
            [3,4,-2],
            [3,2,0]])
print(X,'\n')
print(Y)

[[ 3  2 -1]
 [ 4  1  1]] 

[[ 2 -1  1]
 [ 3  4 -2]
 [ 3  2  0]]


In [19]:
Z=np.dot(X,Y)
Z


array([[ 9,  3, -1],
       [14,  2,  2]])

Algebra liniowa(wyznacznik, macierz jednostkowa,odwrotna i transponowana):

In [22]:
A=np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10.0

ślad macierzy to jest suma na przekatnej

In [23]:
A=np.array([[2,4],[-1,3]])
np.trace(A)

5

Macierz jednostkowa:

In [24]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna:

In [25]:
B=np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [26]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [0]:
Macierz transponowana(zamienia wiersze na kolumny i kolumny na wiersze):


In [27]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [28]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiazywanie ukladow rownan:

In [30]:
A=np.array([[2,4],[1,-1]])
B=np.array([[10],[-1]])
print(A,'\n')
print(B)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [35]:
A_inv=np.linalg.inv(A)
X=np.dot(A_inv,B)
X


array([[1.],
       [2.]])

In [36]:
X.shape

(2, 1)

Funkcje staystyczne:


In [37]:
price=np.array([[12.40,13.50,11.40,12.60,1000],
                [12.50,13.00,14.00,12.40,2000],
                [12.30,13.60,14.20,12.20,1500]])
print(price)

[[  12.4   13.5   11.4   12.6 1000. ]
 [  12.5   13.    14.    12.4 2000. ]
 [  12.3   13.6   14.2   12.2 1500. ]]


In [38]:
price.sum()

4654.1

In [39]:
price.sum(axis=0)

array([  37.2,   40.1,   39.6,   37.2, 4500. ])

In [40]:
price.sum(axis=1)

array([1049.9, 2051.9, 1552.3])

In [42]:
np.min(price, axis=1)

array([11.4, 12.4, 12.2])

In [44]:
np.max(price, axis=0)

array([  12.5,   13.6,   14.2,   12.6, 2000. ])

In [45]:
np.median(price)

13.0

In [46]:
np.mean(price,axis=0)


310.27333333333337

In [48]:
np.std(price,axis=0)

622.2509327344468

In [49]:
np.var(price,axis=0)

array([     0.0067,      0.0689,      1.6267,      0.0267, 166666.6667])